branch          = "main"
location        = "europe-west3"
project         = "fake-client-project"
project_number  = "895133031100"
cloudbuild_file = "cloudbuild_dev.yaml"
cloudbuild_sa   = "895133031100@cloudbuild.gserviceaccount.com"
env_suffix      = "dev"
